Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false  

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

AllCops:
  Exclude:
    - './test/**/*'
    - './*'