# frozen_string_literal: true
require_relative "order_line_item_tax_type"
require_relative "money"
require_relative "order_line_item_tax_scope"
require "ostruct"
require "json"

module SquareApiClient
# Represents a tax that applies to one or more line item in the order.
#  Fixed-amount, order-scoped taxes are distributed across all non-zero line item
#  totals.
#  The amount distributed to each line item is relative to the amount the item
#  contributes to the order subtotal.
  class OrderLineItemTax
  # @return [String] A unique ID that identifies the tax only within this order.
    attr_reader :uid
  # @return [String] The catalog object ID referencing [CatalogTax](entity:CatalogTax).
    attr_reader :catalog_object_id
  # @return [Long] The version of the catalog object that this tax references.
    attr_reader :catalog_version
  # @return [String] The tax's name.
    attr_reader :name
  # @return [SquareApiClient::OrderLineItemTaxType] Indicates the calculation method used to apply the tax.
#  See [OrderLineItemTaxType](#type-orderlineitemtaxtype) for possible values
    attr_reader :type
  # @return [String] The percentage of the tax, as a string representation of a decimal
#  number. For example, a value of `"7.25"` corresponds to a percentage of
#  7.25%.
    attr_reader :percentage
  # @return [Hash{String => String}] Application-defined data attached to this tax. Metadata fields are intended
#  to store descriptive references or associations with an entity in another system
#  or store brief
#  information about the object. Square does not process this field; it only stores
#  and returns it
#  in relevant API calls. Do not use metadata to store any sensitive information
#  (such as personally
#  identifiable information or card details).
#  Keys written by applications must be 60 characters or less and must be in the
#  character set
#  `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These
#  keys are prefixed
#  with a namespace, separated from the key with a ':' character.
#  Values have a maximum length of 255 characters.
#  An application can have up to 10 entries per metadata field.
#  Entries written by applications are private and can only be read or modified by
#  the same
#  application.
#  For more information, see
#  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    attr_reader :metadata
  # @return [SquareApiClient::Money] The amount of money applied to the order by the tax.
#  - For percentage-based taxes, `applied_money` is the money
#  calculated using the percentage.
    attr_reader :applied_money
  # @return [SquareApiClient::OrderLineItemTaxScope] Indicates the level at which the tax applies. For `ORDER` scoped taxes,
#  Square generates references in `applied_taxes` on all order line items that do
#  not have them. For `LINE_ITEM` scoped taxes, the tax only applies to line items
#  with references in their `applied_taxes` field.
#  This field is immutable. To change the scope, you must delete the tax and
#  re-add it as a new tax.
#  See [OrderLineItemTaxScope](#type-orderlineitemtaxscope) for possible values
    attr_reader :scope
  # @return [Boolean] Determines whether the tax was automatically applied to the order based on
#  the catalog configuration. For an example, see
#  [Automatically Apply Taxes to an
#  eloper.squareup.com/docs/orders-api/apply-taxes-and-discounts/auto-apply-taxes).
    attr_reader :auto_applied
  # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
  # @return [Object] 
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param uid [String] A unique ID that identifies the tax only within this order.
    # @param catalog_object_id [String] The catalog object ID referencing [CatalogTax](entity:CatalogTax).
    # @param catalog_version [Long] The version of the catalog object that this tax references.
    # @param name [String] The tax's name.
    # @param type [SquareApiClient::OrderLineItemTaxType] Indicates the calculation method used to apply the tax.
#  See [OrderLineItemTaxType](#type-orderlineitemtaxtype) for possible values
    # @param percentage [String] The percentage of the tax, as a string representation of a decimal
#  number. For example, a value of `"7.25"` corresponds to a percentage of
#  7.25%.
    # @param metadata [Hash{String => String}] Application-defined data attached to this tax. Metadata fields are intended
#  to store descriptive references or associations with an entity in another system
#  or store brief
#  information about the object. Square does not process this field; it only stores
#  and returns it
#  in relevant API calls. Do not use metadata to store any sensitive information
#  (such as personally
#  identifiable information or card details).
#  Keys written by applications must be 60 characters or less and must be in the
#  character set
#  `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These
#  keys are prefixed
#  with a namespace, separated from the key with a ':' character.
#  Values have a maximum length of 255 characters.
#  An application can have up to 10 entries per metadata field.
#  Entries written by applications are private and can only be read or modified by
#  the same
#  application.
#  For more information, see
#  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    # @param applied_money [SquareApiClient::Money] The amount of money applied to the order by the tax.
#  - For percentage-based taxes, `applied_money` is the money
#  calculated using the percentage.
    # @param scope [SquareApiClient::OrderLineItemTaxScope] Indicates the level at which the tax applies. For `ORDER` scoped taxes,
#  Square generates references in `applied_taxes` on all order line items that do
#  not have them. For `LINE_ITEM` scoped taxes, the tax only applies to line items
#  with references in their `applied_taxes` field.
#  This field is immutable. To change the scope, you must delete the tax and
#  re-add it as a new tax.
#  See [OrderLineItemTaxScope](#type-orderlineitemtaxscope) for possible values
    # @param auto_applied [Boolean] Determines whether the tax was automatically applied to the order based on
#  the catalog configuration. For an example, see
#  [Automatically Apply Taxes to an
#  eloper.squareup.com/docs/orders-api/apply-taxes-and-discounts/auto-apply-taxes).
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [SquareApiClient::OrderLineItemTax]
    def initialize(uid: OMIT, catalog_object_id: OMIT, catalog_version: OMIT, name: OMIT, type: OMIT, percentage: OMIT, metadata: OMIT, applied_money: OMIT, scope: OMIT, auto_applied: OMIT, additional_properties: nil)
      @uid = uid if uid != OMIT
      @catalog_object_id = catalog_object_id if catalog_object_id != OMIT
      @catalog_version = catalog_version if catalog_version != OMIT
      @name = name if name != OMIT
      @type = type if type != OMIT
      @percentage = percentage if percentage != OMIT
      @metadata = metadata if metadata != OMIT
      @applied_money = applied_money if applied_money != OMIT
      @scope = scope if scope != OMIT
      @auto_applied = auto_applied if auto_applied != OMIT
      @additional_properties = additional_properties
      @_field_set = { "uid": uid, "catalog_object_id": catalog_object_id, "catalog_version": catalog_version, "name": name, "type": type, "percentage": percentage, "metadata": metadata, "applied_money": applied_money, "scope": scope, "auto_applied": auto_applied }.reject do | _k, v |
  v == OMIT
end
    end
# Deserialize a JSON object to an instance of OrderLineItemTax
    #
    # @param json_object [String] 
    # @return [SquareApiClient::OrderLineItemTax]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      uid = parsed_json["uid"]
      catalog_object_id = parsed_json["catalog_object_id"]
      catalog_version = parsed_json["catalog_version"]
      name = parsed_json["name"]
      type = parsed_json["type"]
      percentage = parsed_json["percentage"]
      metadata = parsed_json["metadata"]
      unless parsed_json["applied_money"].nil?
        applied_money = parsed_json["applied_money"].to_json
        applied_money = SquareApiClient::Money.from_json(json_object: applied_money)
      else
        applied_money = nil
      end
      scope = parsed_json["scope"]
      auto_applied = parsed_json["auto_applied"]
      new(
        uid: uid,
        catalog_object_id: catalog_object_id,
        catalog_version: catalog_version,
        name: name,
        type: type,
        percentage: percentage,
        metadata: metadata,
        applied_money: applied_money,
        scope: scope,
        auto_applied: auto_applied,
        additional_properties: struct
      )
    end
# Serialize an instance of OrderLineItemTax to a JSON object
    #
    # @return [String]
    def to_json
      @_field_set&.to_json
    end
# Leveraged for Union-type generation, validate_raw attempts to parse the given
#  hash and check each fields type against the current object's property
#  definitions.
    #
    # @param obj [Object] 
    # @return [Void]
    def self.validate_raw(obj:)
      obj.uid&.is_a?(String) != false || raise("Passed value for field obj.uid is not the expected type, validation failed.")
      obj.catalog_object_id&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_id is not the expected type, validation failed.")
      obj.catalog_version&.is_a?(Long) != false || raise("Passed value for field obj.catalog_version is not the expected type, validation failed.")
      obj.name&.is_a?(String) != false || raise("Passed value for field obj.name is not the expected type, validation failed.")
      obj.type&.is_a?(SquareApiClient::OrderLineItemTaxType) != false || raise("Passed value for field obj.type is not the expected type, validation failed.")
      obj.percentage&.is_a?(String) != false || raise("Passed value for field obj.percentage is not the expected type, validation failed.")
      obj.metadata&.is_a?(Hash) != false || raise("Passed value for field obj.metadata is not the expected type, validation failed.")
      obj.applied_money.nil? || SquareApiClient::Money.validate_raw(obj: obj.applied_money)
      obj.scope&.is_a?(SquareApiClient::OrderLineItemTaxScope) != false || raise("Passed value for field obj.scope is not the expected type, validation failed.")
      obj.auto_applied&.is_a?(Boolean) != false || raise("Passed value for field obj.auto_applied is not the expected type, validation failed.")
    end
  end
end