# square
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Square
  # HTTP Methods Enumeration.
  class HttpMethodEnum
    HTTPMETHODENUM = [GET = 'GET'.freeze, POST = 'POST'.freeze,
                      PUT = 'PUT'.freeze, PATCH = 'PATCH'.freeze,
                      DELETE = 'DELETE'.freeze, HEAD = 'HEAD'.freeze].freeze
  end
end
