# frozen_string_literal: true

module Square
  module Types
    # Represents the payment details of a card to be used for payments. These
    # details are determined by the payment token generated by Web Payments SDK.
    class Card < Internal::Types::Model
      field :id, String, optional: true, nullable: false
      field :card_brand, Square::CardBrand, optional: true, nullable: false
      field :last_4, String, optional: true, nullable: false
      field :exp_month, Integer, optional: true, nullable: false
      field :exp_year, Integer, optional: true, nullable: false
      field :cardholder_name, String, optional: true, nullable: false
      field :billing_address, Square::Address, optional: true, nullable: false
      field :fingerprint, String, optional: true, nullable: false
      field :customer_id, String, optional: true, nullable: false
      field :merchant_id, String, optional: true, nullable: false
      field :reference_id, String, optional: true, nullable: false
      field :enabled, Internal::Types::Boolean, optional: true, nullable: false
      field :card_type, Square::CardType, optional: true, nullable: false
      field :prepaid_type, Square::CardPrepaidType, optional: true, nullable: false
      field :bin, String, optional: true, nullable: false
      field :version, Integer, optional: true, nullable: false
      field :card_co_brand, Square::CardCoBrand, optional: true, nullable: false
      field :issuer_alert, String, optional: true, nullable: false
      field :issuer_alert_at, String, optional: true, nullable: false
      field :hsa_fsa, Internal::Types::Boolean, optional: true, nullable: false

    end
  end
end
