
module Square
  module Types
    module CustomerCreationSource
      extends Square::Internal::Types::Enum
      OTHER = "OTHER"
      APPOINTMENTS = "APPOINTMENTS"
      COUPON = "COUPON"
      DELETION_RECOVERY = "DELETION_RECOVERY"
      DIRECTORY = "DIRECTORY"
      EGIFTING = "EGIFTING"
      EMAIL_COLLECTION = "EMAIL_COLLECTION"
      FEEDBACK = "FEEDBACK"
      IMPORT = "IMPORT"
      INVOICES = "INVOICES"
      LOYALTY = "LOYALTY"
      MARKETING = "MARKETING"
      MERGE = "MERGE"
      ONLINE_STORE = "ONLINE_STORE"
      INSTANT_PROFILE = "INSTANT_PROFILE"
      TERMINAL = "TERMINAL"
      THIRD_PARTY = "THIRD_PARTY"
      THIRD_PARTY_IMPORT = "THIRD_PARTY_IMPORT"
      UNMERGE_RECOVERY = "UNMERGE_RECOVERY"end
  end
end
