
module Square
  class DisputeEvidenceType
    includes Square::Internal::Types::Enum
    GENERIC_EVIDENCE = "GENERIC_EVIDENCE"
    ONLINE_OR_APP_ACCESS_LOG = "ONLINE_OR_APP_ACCESS_LOG"
    AUTHORIZATION_DOCUMENTATION = "AUTHORIZATION_DOCUMENTATION"
    CANCELLATION_OR_REFUND_DOCUMENTATION = "CANCELLATION_OR_REFUND_DOCUMENTATION"
    CARDHOLDER_COMMUNICATION = "CARDHOLDER_COMMUNICATION"
    CARDHOLDER_INFORMATION = "CARDHOLDER_INFORMATION"
    PURCHASE_ACKNOWLEDGEMENT = "PURCHASE_ACKNOWLEDGEMENT"
    DUPLICATE_CHARGE_DOCUMENTATION = "DUPLICATE_CHARGE_DOCUMENTATION"
    PRODUCT_OR_SERVICE_DESCRIPTION = "PRODUCT_OR_SERVICE_DESCRIPTION"
    RECEIPT = "RECEIPT"
    SERVICE_RECEIVED_DOCUMENTATION = "SERVICE_RECEIVED_DOCUMENTATION"
    PROOF_OF_DELIVERY_DOCUMENTATION = "PROOF_OF_DELIVERY_DOCUMENTATION"
    RELATED_TRANSACTION_DOCUMENTATION = "RELATED_TRANSACTION_DOCUMENTATION"
    REBUTTAL_EXPLANATION = "REBUTTAL_EXPLANATION"
    TRACKING_NUMBER = "TRACKING_NUMBER"
  end
end
