# frozen_string_literal: true
require_relative "inventory_state"
require_relative "money"
require_relative "source_application"
require_relative "inventory_adjustment_group"
require "ostruct"
require "json"

module square.rb
# Represents a change in state or quantity of product inventory at a
#  particular time and location.
  class InventoryAdjustment
  # @return [String] A unique ID generated by Square for the
#  `InventoryAdjustment`.
    attr_reader :id
  # @return [String] An optional ID provided by the application to tie the
#  `InventoryAdjustment` to an external
#  system.
    attr_reader :reference_id
  # @return [square.rb::InventoryState] The [inventory state](entity:InventoryState) of the related quantity
#  of items before the adjustment.
#  See [InventoryState](#type-inventorystate) for possible values
    attr_reader :from_state
  # @return [square.rb::InventoryState] The [inventory state](entity:InventoryState) of the related quantity
#  of items after the adjustment.
#  See [InventoryState](#type-inventorystate) for possible values
    attr_reader :to_state
  # @return [String] The Square-generated ID of the [Location](entity:Location) where the related
#  quantity of items is being tracked.
    attr_reader :location_id
  # @return [String] The Square-generated ID of the
#  [CatalogObject](entity:CatalogObject) being tracked.
    attr_reader :catalog_object_id
  # @return [String] The [type](entity:CatalogObjectType) of the
#  [CatalogObject](entity:CatalogObject) being tracked.
#  The Inventory API supports setting and reading the `"catalog_object_type":
#  "ITEM_VARIATION"` field value.
#  In addition, it can also read the `"catalog_object_type": "ITEM"` field value
#  that is set by the Square Restaurants app.
    attr_reader :catalog_object_type
  # @return [String] The number of items affected by the adjustment as a decimal string.
#  Can support up to 5 digits after the decimal point.
    attr_reader :quantity
  # @return [square.rb::Money] The total price paid for goods associated with the
#  adjustment. Present if and only if `to_state` is `SOLD`. Always
#  non-negative.
    attr_reader :total_price_money
  # @return [String] A client-generated RFC 3339-formatted timestamp that indicates when
#  the inventory adjustment took place. For inventory adjustment updates, the
#  `occurred_at`
#  timestamp cannot be older than 24 hours or in the future relative to the
#  time of the request.
    attr_reader :occurred_at
  # @return [String] An RFC 3339-formatted timestamp that indicates when the inventory adjustment is
#  received.
    attr_reader :created_at
  # @return [square.rb::SourceApplication] Information about the application that caused the
#  inventory adjustment.
    attr_reader :source
  # @return [String] The Square-generated ID of the [Employee](entity:Employee) responsible for the
#  inventory adjustment.
    attr_reader :employee_id
  # @return [String] The Square-generated ID of the [Team Member](entity:TeamMember) responsible for
#  the
#  inventory adjustment.
    attr_reader :team_member_id
  # @return [String] The Square-generated ID of the [Transaction](entity:Transaction) that
#  caused the adjustment. Only relevant for payment-related state
#  transitions.
    attr_reader :transaction_id
  # @return [String] The Square-generated ID of the [Refund](entity:Refund) that
#  caused the adjustment. Only relevant for refund-related state
#  transitions.
    attr_reader :refund_id
  # @return [String] The Square-generated ID of the purchase order that caused the
#  adjustment. Only relevant for state transitions from the Square for Retail
#  app.
    attr_reader :purchase_order_id
  # @return [String] The Square-generated ID of the goods receipt that caused the
#  adjustment. Only relevant for state transitions from the Square for Retail
#  app.
    attr_reader :goods_receipt_id
  # @return [square.rb::InventoryAdjustmentGroup] An adjustment group bundling the related adjustments of item variations through
#  stock conversions in a single inventory event.
    attr_reader :adjustment_group
  # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
  # @return [Object] 
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param id [String] A unique ID generated by Square for the
#  `InventoryAdjustment`.
    # @param reference_id [String] An optional ID provided by the application to tie the
#  `InventoryAdjustment` to an external
#  system.
    # @param from_state [square.rb::InventoryState] The [inventory state](entity:InventoryState) of the related quantity
#  of items before the adjustment.
#  See [InventoryState](#type-inventorystate) for possible values
    # @param to_state [square.rb::InventoryState] The [inventory state](entity:InventoryState) of the related quantity
#  of items after the adjustment.
#  See [InventoryState](#type-inventorystate) for possible values
    # @param location_id [String] The Square-generated ID of the [Location](entity:Location) where the related
#  quantity of items is being tracked.
    # @param catalog_object_id [String] The Square-generated ID of the
#  [CatalogObject](entity:CatalogObject) being tracked.
    # @param catalog_object_type [String] The [type](entity:CatalogObjectType) of the
#  [CatalogObject](entity:CatalogObject) being tracked.
#  The Inventory API supports setting and reading the `"catalog_object_type":
#  "ITEM_VARIATION"` field value.
#  In addition, it can also read the `"catalog_object_type": "ITEM"` field value
#  that is set by the Square Restaurants app.
    # @param quantity [String] The number of items affected by the adjustment as a decimal string.
#  Can support up to 5 digits after the decimal point.
    # @param total_price_money [square.rb::Money] The total price paid for goods associated with the
#  adjustment. Present if and only if `to_state` is `SOLD`. Always
#  non-negative.
    # @param occurred_at [String] A client-generated RFC 3339-formatted timestamp that indicates when
#  the inventory adjustment took place. For inventory adjustment updates, the
#  `occurred_at`
#  timestamp cannot be older than 24 hours or in the future relative to the
#  time of the request.
    # @param created_at [String] An RFC 3339-formatted timestamp that indicates when the inventory adjustment is
#  received.
    # @param source [square.rb::SourceApplication] Information about the application that caused the
#  inventory adjustment.
    # @param employee_id [String] The Square-generated ID of the [Employee](entity:Employee) responsible for the
#  inventory adjustment.
    # @param team_member_id [String] The Square-generated ID of the [Team Member](entity:TeamMember) responsible for
#  the
#  inventory adjustment.
    # @param transaction_id [String] The Square-generated ID of the [Transaction](entity:Transaction) that
#  caused the adjustment. Only relevant for payment-related state
#  transitions.
    # @param refund_id [String] The Square-generated ID of the [Refund](entity:Refund) that
#  caused the adjustment. Only relevant for refund-related state
#  transitions.
    # @param purchase_order_id [String] The Square-generated ID of the purchase order that caused the
#  adjustment. Only relevant for state transitions from the Square for Retail
#  app.
    # @param goods_receipt_id [String] The Square-generated ID of the goods receipt that caused the
#  adjustment. Only relevant for state transitions from the Square for Retail
#  app.
    # @param adjustment_group [square.rb::InventoryAdjustmentGroup] An adjustment group bundling the related adjustments of item variations through
#  stock conversions in a single inventory event.
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [square.rb::InventoryAdjustment]
    def initialize(id: OMIT, reference_id: OMIT, from_state: OMIT, to_state: OMIT, location_id: OMIT, catalog_object_id: OMIT, catalog_object_type: OMIT, quantity: OMIT, total_price_money: OMIT, occurred_at: OMIT, created_at: OMIT, source: OMIT, employee_id: OMIT, team_member_id: OMIT, transaction_id: OMIT, refund_id: OMIT, purchase_order_id: OMIT, goods_receipt_id: OMIT, adjustment_group: OMIT, additional_properties: nil)
      @id = id if id != OMIT
      @reference_id = reference_id if reference_id != OMIT
      @from_state = from_state if from_state != OMIT
      @to_state = to_state if to_state != OMIT
      @location_id = location_id if location_id != OMIT
      @catalog_object_id = catalog_object_id if catalog_object_id != OMIT
      @catalog_object_type = catalog_object_type if catalog_object_type != OMIT
      @quantity = quantity if quantity != OMIT
      @total_price_money = total_price_money if total_price_money != OMIT
      @occurred_at = occurred_at if occurred_at != OMIT
      @created_at = created_at if created_at != OMIT
      @source = source if source != OMIT
      @employee_id = employee_id if employee_id != OMIT
      @team_member_id = team_member_id if team_member_id != OMIT
      @transaction_id = transaction_id if transaction_id != OMIT
      @refund_id = refund_id if refund_id != OMIT
      @purchase_order_id = purchase_order_id if purchase_order_id != OMIT
      @goods_receipt_id = goods_receipt_id if goods_receipt_id != OMIT
      @adjustment_group = adjustment_group if adjustment_group != OMIT
      @additional_properties = additional_properties
      @_field_set = { "id": id, "reference_id": reference_id, "from_state": from_state, "to_state": to_state, "location_id": location_id, "catalog_object_id": catalog_object_id, "catalog_object_type": catalog_object_type, "quantity": quantity, "total_price_money": total_price_money, "occurred_at": occurred_at, "created_at": created_at, "source": source, "employee_id": employee_id, "team_member_id": team_member_id, "transaction_id": transaction_id, "refund_id": refund_id, "purchase_order_id": purchase_order_id, "goods_receipt_id": goods_receipt_id, "adjustment_group": adjustment_group }.reject do | _k, v |
  v == OMIT
end
    end
# Deserialize a JSON object to an instance of InventoryAdjustment
    #
    # @param json_object [String] 
    # @return [square.rb::InventoryAdjustment]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      id = parsed_json["id"]
      reference_id = parsed_json["reference_id"]
      from_state = parsed_json["from_state"]
      to_state = parsed_json["to_state"]
      location_id = parsed_json["location_id"]
      catalog_object_id = parsed_json["catalog_object_id"]
      catalog_object_type = parsed_json["catalog_object_type"]
      quantity = parsed_json["quantity"]
      unless parsed_json["total_price_money"].nil?
        total_price_money = parsed_json["total_price_money"].to_json
        total_price_money = square.rb::Money.from_json(json_object: total_price_money)
      else
        total_price_money = nil
      end
      occurred_at = parsed_json["occurred_at"]
      created_at = parsed_json["created_at"]
      unless parsed_json["source"].nil?
        source = parsed_json["source"].to_json
        source = square.rb::SourceApplication.from_json(json_object: source)
      else
        source = nil
      end
      employee_id = parsed_json["employee_id"]
      team_member_id = parsed_json["team_member_id"]
      transaction_id = parsed_json["transaction_id"]
      refund_id = parsed_json["refund_id"]
      purchase_order_id = parsed_json["purchase_order_id"]
      goods_receipt_id = parsed_json["goods_receipt_id"]
      unless parsed_json["adjustment_group"].nil?
        adjustment_group = parsed_json["adjustment_group"].to_json
        adjustment_group = square.rb::InventoryAdjustmentGroup.from_json(json_object: adjustment_group)
      else
        adjustment_group = nil
      end
      new(
        id: id,
        reference_id: reference_id,
        from_state: from_state,
        to_state: to_state,
        location_id: location_id,
        catalog_object_id: catalog_object_id,
        catalog_object_type: catalog_object_type,
        quantity: quantity,
        total_price_money: total_price_money,
        occurred_at: occurred_at,
        created_at: created_at,
        source: source,
        employee_id: employee_id,
        team_member_id: team_member_id,
        transaction_id: transaction_id,
        refund_id: refund_id,
        purchase_order_id: purchase_order_id,
        goods_receipt_id: goods_receipt_id,
        adjustment_group: adjustment_group,
        additional_properties: struct
      )
    end
# Serialize an instance of InventoryAdjustment to a JSON object
    #
    # @return [String]
    def to_json
      @_field_set&.to_json
    end
# Leveraged for Union-type generation, validate_raw attempts to parse the given
#  hash and check each fields type against the current object's property
#  definitions.
    #
    # @param obj [Object] 
    # @return [Void]
    def self.validate_raw(obj:)
      obj.id&.is_a?(String) != false || raise("Passed value for field obj.id is not the expected type, validation failed.")
      obj.reference_id&.is_a?(String) != false || raise("Passed value for field obj.reference_id is not the expected type, validation failed.")
      obj.from_state&.is_a?(square.rb::InventoryState) != false || raise("Passed value for field obj.from_state is not the expected type, validation failed.")
      obj.to_state&.is_a?(square.rb::InventoryState) != false || raise("Passed value for field obj.to_state is not the expected type, validation failed.")
      obj.location_id&.is_a?(String) != false || raise("Passed value for field obj.location_id is not the expected type, validation failed.")
      obj.catalog_object_id&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_id is not the expected type, validation failed.")
      obj.catalog_object_type&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_type is not the expected type, validation failed.")
      obj.quantity&.is_a?(String) != false || raise("Passed value for field obj.quantity is not the expected type, validation failed.")
      obj.total_price_money.nil? || square.rb::Money.validate_raw(obj: obj.total_price_money)
      obj.occurred_at&.is_a?(String) != false || raise("Passed value for field obj.occurred_at is not the expected type, validation failed.")
      obj.created_at&.is_a?(String) != false || raise("Passed value for field obj.created_at is not the expected type, validation failed.")
      obj.source.nil? || square.rb::SourceApplication.validate_raw(obj: obj.source)
      obj.employee_id&.is_a?(String) != false || raise("Passed value for field obj.employee_id is not the expected type, validation failed.")
      obj.team_member_id&.is_a?(String) != false || raise("Passed value for field obj.team_member_id is not the expected type, validation failed.")
      obj.transaction_id&.is_a?(String) != false || raise("Passed value for field obj.transaction_id is not the expected type, validation failed.")
      obj.refund_id&.is_a?(String) != false || raise("Passed value for field obj.refund_id is not the expected type, validation failed.")
      obj.purchase_order_id&.is_a?(String) != false || raise("Passed value for field obj.purchase_order_id is not the expected type, validation failed.")
      obj.goods_receipt_id&.is_a?(String) != false || raise("Passed value for field obj.goods_receipt_id is not the expected type, validation failed.")
      obj.adjustment_group.nil? || square.rb::InventoryAdjustmentGroup.validate_raw(obj: obj.adjustment_group)
    end
  end
end