# frozen_string_literal: true
require_relative "inventory_state"
require_relative "source_application"
require "ostruct"
require "json"

module SquareApiClient
# Represents the transfer of a quantity of product inventory at a
#  particular time from one location to another.
  class InventoryTransfer
  # @return [String] A unique ID generated by Square for the
#  `InventoryTransfer`.
    attr_reader :id
  # @return [String] An optional ID provided by the application to tie the
#  `InventoryTransfer` to an external system.
    attr_reader :reference_id
  # @return [SquareApiClient::InventoryState] The [inventory state](entity:InventoryState) for the quantity of
#  items being transferred.
#  See [InventoryState](#type-inventorystate) for possible values
    attr_reader :state
  # @return [String] The Square-generated ID of the [Location](entity:Location) where the related
#  quantity of items was tracked before the transfer.
    attr_reader :from_location_id
  # @return [String] The Square-generated ID of the [Location](entity:Location) where the related
#  quantity of items was tracked after the transfer.
    attr_reader :to_location_id
  # @return [String] The Square-generated ID of the
#  [CatalogObject](entity:CatalogObject) being tracked.
    attr_reader :catalog_object_id
  # @return [String] The [type](entity:CatalogObjectType) of the
#  [CatalogObject](entity:CatalogObject) being tracked.
#  The Inventory API supports setting and reading the `"catalog_object_type":
#  "ITEM_VARIATION"` field value.
#  In addition, it can also read the `"catalog_object_type": "ITEM"` field value
#  that is set by the Square Restaurants app.
    attr_reader :catalog_object_type
  # @return [String] The number of items affected by the transfer as a decimal string.
#  Can support up to 5 digits after the decimal point.
    attr_reader :quantity
  # @return [String] A client-generated RFC 3339-formatted timestamp that indicates when
#  the transfer took place. For write actions, the `occurred_at` timestamp
#  cannot be older than 24 hours or in the future relative to the time of the
#  request.
    attr_reader :occurred_at
  # @return [String] An RFC 3339-formatted timestamp that indicates when Square
#  received the transfer request.
    attr_reader :created_at
  # @return [SquareApiClient::SourceApplication] Information about the application that initiated the
#  inventory transfer.
    attr_reader :source
  # @return [String] The Square-generated ID of the [Employee](entity:Employee) responsible for the
#  inventory transfer.
    attr_reader :employee_id
  # @return [String] The Square-generated ID of the [Team Member](entity:TeamMember) responsible for
#  the
#  inventory transfer.
    attr_reader :team_member_id
  # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
  # @return [Object] 
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param id [String] A unique ID generated by Square for the
#  `InventoryTransfer`.
    # @param reference_id [String] An optional ID provided by the application to tie the
#  `InventoryTransfer` to an external system.
    # @param state [SquareApiClient::InventoryState] The [inventory state](entity:InventoryState) for the quantity of
#  items being transferred.
#  See [InventoryState](#type-inventorystate) for possible values
    # @param from_location_id [String] The Square-generated ID of the [Location](entity:Location) where the related
#  quantity of items was tracked before the transfer.
    # @param to_location_id [String] The Square-generated ID of the [Location](entity:Location) where the related
#  quantity of items was tracked after the transfer.
    # @param catalog_object_id [String] The Square-generated ID of the
#  [CatalogObject](entity:CatalogObject) being tracked.
    # @param catalog_object_type [String] The [type](entity:CatalogObjectType) of the
#  [CatalogObject](entity:CatalogObject) being tracked.
#  The Inventory API supports setting and reading the `"catalog_object_type":
#  "ITEM_VARIATION"` field value.
#  In addition, it can also read the `"catalog_object_type": "ITEM"` field value
#  that is set by the Square Restaurants app.
    # @param quantity [String] The number of items affected by the transfer as a decimal string.
#  Can support up to 5 digits after the decimal point.
    # @param occurred_at [String] A client-generated RFC 3339-formatted timestamp that indicates when
#  the transfer took place. For write actions, the `occurred_at` timestamp
#  cannot be older than 24 hours or in the future relative to the time of the
#  request.
    # @param created_at [String] An RFC 3339-formatted timestamp that indicates when Square
#  received the transfer request.
    # @param source [SquareApiClient::SourceApplication] Information about the application that initiated the
#  inventory transfer.
    # @param employee_id [String] The Square-generated ID of the [Employee](entity:Employee) responsible for the
#  inventory transfer.
    # @param team_member_id [String] The Square-generated ID of the [Team Member](entity:TeamMember) responsible for
#  the
#  inventory transfer.
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [SquareApiClient::InventoryTransfer]
    def initialize(id: OMIT, reference_id: OMIT, state: OMIT, from_location_id: OMIT, to_location_id: OMIT, catalog_object_id: OMIT, catalog_object_type: OMIT, quantity: OMIT, occurred_at: OMIT, created_at: OMIT, source: OMIT, employee_id: OMIT, team_member_id: OMIT, additional_properties: nil)
      @id = id if id != OMIT
      @reference_id = reference_id if reference_id != OMIT
      @state = state if state != OMIT
      @from_location_id = from_location_id if from_location_id != OMIT
      @to_location_id = to_location_id if to_location_id != OMIT
      @catalog_object_id = catalog_object_id if catalog_object_id != OMIT
      @catalog_object_type = catalog_object_type if catalog_object_type != OMIT
      @quantity = quantity if quantity != OMIT
      @occurred_at = occurred_at if occurred_at != OMIT
      @created_at = created_at if created_at != OMIT
      @source = source if source != OMIT
      @employee_id = employee_id if employee_id != OMIT
      @team_member_id = team_member_id if team_member_id != OMIT
      @additional_properties = additional_properties
      @_field_set = { "id": id, "reference_id": reference_id, "state": state, "from_location_id": from_location_id, "to_location_id": to_location_id, "catalog_object_id": catalog_object_id, "catalog_object_type": catalog_object_type, "quantity": quantity, "occurred_at": occurred_at, "created_at": created_at, "source": source, "employee_id": employee_id, "team_member_id": team_member_id }.reject do | _k, v |
  v == OMIT
end
    end
# Deserialize a JSON object to an instance of InventoryTransfer
    #
    # @param json_object [String] 
    # @return [SquareApiClient::InventoryTransfer]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      id = parsed_json["id"]
      reference_id = parsed_json["reference_id"]
      state = parsed_json["state"]
      from_location_id = parsed_json["from_location_id"]
      to_location_id = parsed_json["to_location_id"]
      catalog_object_id = parsed_json["catalog_object_id"]
      catalog_object_type = parsed_json["catalog_object_type"]
      quantity = parsed_json["quantity"]
      occurred_at = parsed_json["occurred_at"]
      created_at = parsed_json["created_at"]
      unless parsed_json["source"].nil?
        source = parsed_json["source"].to_json
        source = SquareApiClient::SourceApplication.from_json(json_object: source)
      else
        source = nil
      end
      employee_id = parsed_json["employee_id"]
      team_member_id = parsed_json["team_member_id"]
      new(
        id: id,
        reference_id: reference_id,
        state: state,
        from_location_id: from_location_id,
        to_location_id: to_location_id,
        catalog_object_id: catalog_object_id,
        catalog_object_type: catalog_object_type,
        quantity: quantity,
        occurred_at: occurred_at,
        created_at: created_at,
        source: source,
        employee_id: employee_id,
        team_member_id: team_member_id,
        additional_properties: struct
      )
    end
# Serialize an instance of InventoryTransfer to a JSON object
    #
    # @return [String]
    def to_json
      @_field_set&.to_json
    end
# Leveraged for Union-type generation, validate_raw attempts to parse the given
#  hash and check each fields type against the current object's property
#  definitions.
    #
    # @param obj [Object] 
    # @return [Void]
    def self.validate_raw(obj:)
      obj.id&.is_a?(String) != false || raise("Passed value for field obj.id is not the expected type, validation failed.")
      obj.reference_id&.is_a?(String) != false || raise("Passed value for field obj.reference_id is not the expected type, validation failed.")
      obj.state&.is_a?(SquareApiClient::InventoryState) != false || raise("Passed value for field obj.state is not the expected type, validation failed.")
      obj.from_location_id&.is_a?(String) != false || raise("Passed value for field obj.from_location_id is not the expected type, validation failed.")
      obj.to_location_id&.is_a?(String) != false || raise("Passed value for field obj.to_location_id is not the expected type, validation failed.")
      obj.catalog_object_id&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_id is not the expected type, validation failed.")
      obj.catalog_object_type&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_type is not the expected type, validation failed.")
      obj.quantity&.is_a?(String) != false || raise("Passed value for field obj.quantity is not the expected type, validation failed.")
      obj.occurred_at&.is_a?(String) != false || raise("Passed value for field obj.occurred_at is not the expected type, validation failed.")
      obj.created_at&.is_a?(String) != false || raise("Passed value for field obj.created_at is not the expected type, validation failed.")
      obj.source.nil? || SquareApiClient::SourceApplication.validate_raw(obj: obj.source)
      obj.employee_id&.is_a?(String) != false || raise("Passed value for field obj.employee_id is not the expected type, validation failed.")
      obj.team_member_id&.is_a?(String) != false || raise("Passed value for field obj.team_member_id is not the expected type, validation failed.")
    end
  end
end