# frozen_string_literal: true

module square.rb
# Defines whether the event was generated by the Square Point of Sale.
  class LoyaltyEventSource

    SQUARE = "SQUARE"
    LOYALTY_API = "LOYALTY_API"

  end
end