
module Square
  class MeasurementUnitWeight
    include Square::Internal::Types::Enum
    IMPERIAL_WEIGHT_OUNCE = "IMPERIAL_WEIGHT_OUNCE"
    IMPERIAL_POUND = "IMPERIAL_POUND"
    IMPERIAL_STONE = "IMPERIAL_STONE"
    METRIC_MILLIGRAM = "METRIC_MILLIGRAM"
    METRIC_GRAM = "METRIC_GRAM"
    METRIC_KILOGRAM = "METRIC_KILOGRAM"
  end
end
