# frozen_string_literal: true

module square.rb
# The unit of volume used to measure a quantity.
  class MeasurementUnitVolume

    GENERIC_FLUID_OUNCE = "GENERIC_FLUID_OUNCE"
    GENERIC_SHOT = "GENERIC_SHOT"
    GENERIC_CUP = "GENERIC_CUP"
    GENERIC_PINT = "GENERIC_PINT"
    GENERIC_QUART = "GENERIC_QUART"
    GENERIC_GALLON = "GENERIC_GALLON"
    IMPERIAL_CUBIC_INCH = "IMPERIAL_CUBIC_INCH"
    IMPERIAL_CUBIC_FOOT = "IMPERIAL_CUBIC_FOOT"
    IMPERIAL_CUBIC_YARD = "IMPERIAL_CUBIC_YARD"
    METRIC_MILLILITER = "METRIC_MILLILITER"
    METRIC_LITER = "METRIC_LITER"

  end
end