# frozen_string_literal: true

module Square
  module Types
    module MeasurementUnitArea
      extend Square::Internal::Types::Enum

      IMPERIAL_ACRE = "IMPERIAL_ACRE"
      IMPERIAL_SQUARE_INCH = "IMPERIAL_SQUARE_INCH"
      IMPERIAL_SQUARE_FOOT = "IMPERIAL_SQUARE_FOOT"
      IMPERIAL_SQUARE_YARD = "IMPERIAL_SQUARE_YARD"
      IMPERIAL_SQUARE_MILE = "IMPERIAL_SQUARE_MILE"
      METRIC_SQUARE_CENTIMETER = "METRIC_SQUARE_CENTIMETER"
      METRIC_SQUARE_METER = "METRIC_SQUARE_METER"
      METRIC_SQUARE_KILOMETER = "METRIC_SQUARE_KILOMETER"
    end
  end
end
