# frozen_string_literal: true
require_relative "money"
require "ostruct"
require "json"

module square.rb
# A [CatalogModifier](entity:CatalogModifier).
  class OrderLineItemModifier
  # @return [String] A unique ID that identifies the modifier only within this order.
    attr_reader :uid
  # @return [String] The catalog object ID referencing [CatalogModifier](entity:CatalogModifier).
    attr_reader :catalog_object_id
  # @return [Long] The version of the catalog object that this modifier references.
    attr_reader :catalog_version
  # @return [String] The name of the item modifier.
    attr_reader :name
  # @return [String] The quantity of the line item modifier. The modifier quantity can be 0 or more.
#  For example, suppose a restaurant offers a cheeseburger on the menu. When a
#  buyer orders
#  this item, the restaurant records the purchase by creating an `Order` object
#  with a line item
#  for a burger. The line item includes a line item modifier: the name is cheese
#  and the quantity
#  is 1. The buyer has the option to order extra cheese (or no cheese). If the
#  buyer chooses
#  the extra cheese option, the modifier quantity increases to 2. If the buyer does
#  not want
#  any cheese, the modifier quantity is set to 0.
    attr_reader :quantity
  # @return [square.rb::Money] The base price for the modifier.
#  `base_price_money` is required for ad hoc modifiers.
#  If both `catalog_object_id` and `base_price_money` are set, `base_price_money`
#  will
#  override the predefined [CatalogModifier](entity:CatalogModifier) price.
    attr_reader :base_price_money
  # @return [square.rb::Money] The total price of the item modifier for its line item.
#  This is the modifier's `base_price_money` multiplied by the line item's
#  quantity.
    attr_reader :total_price_money
  # @return [Hash{String => String}] Application-defined data attached to this order. Metadata fields are intended
#  to store descriptive references or associations with an entity in another system
#  or store brief
#  information about the object. Square does not process this field; it only stores
#  and returns it
#  in relevant API calls. Do not use metadata to store any sensitive information
#  (such as personally
#  identifiable information or card details).
#  Keys written by applications must be 60 characters or less and must be in the
#  character set
#  `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These
#  keys are prefixed
#  with a namespace, separated from the key with a ':' character.
#  Values have a maximum length of 255 characters.
#  An application can have up to 10 entries per metadata field.
#  Entries written by applications are private and can only be read or modified by
#  the same
#  application.
#  For more information, see
#  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    attr_reader :metadata
  # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
  # @return [Object] 
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param uid [String] A unique ID that identifies the modifier only within this order.
    # @param catalog_object_id [String] The catalog object ID referencing [CatalogModifier](entity:CatalogModifier).
    # @param catalog_version [Long] The version of the catalog object that this modifier references.
    # @param name [String] The name of the item modifier.
    # @param quantity [String] The quantity of the line item modifier. The modifier quantity can be 0 or more.
#  For example, suppose a restaurant offers a cheeseburger on the menu. When a
#  buyer orders
#  this item, the restaurant records the purchase by creating an `Order` object
#  with a line item
#  for a burger. The line item includes a line item modifier: the name is cheese
#  and the quantity
#  is 1. The buyer has the option to order extra cheese (or no cheese). If the
#  buyer chooses
#  the extra cheese option, the modifier quantity increases to 2. If the buyer does
#  not want
#  any cheese, the modifier quantity is set to 0.
    # @param base_price_money [square.rb::Money] The base price for the modifier.
#  `base_price_money` is required for ad hoc modifiers.
#  If both `catalog_object_id` and `base_price_money` are set, `base_price_money`
#  will
#  override the predefined [CatalogModifier](entity:CatalogModifier) price.
    # @param total_price_money [square.rb::Money] The total price of the item modifier for its line item.
#  This is the modifier's `base_price_money` multiplied by the line item's
#  quantity.
    # @param metadata [Hash{String => String}] Application-defined data attached to this order. Metadata fields are intended
#  to store descriptive references or associations with an entity in another system
#  or store brief
#  information about the object. Square does not process this field; it only stores
#  and returns it
#  in relevant API calls. Do not use metadata to store any sensitive information
#  (such as personally
#  identifiable information or card details).
#  Keys written by applications must be 60 characters or less and must be in the
#  character set
#  `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These
#  keys are prefixed
#  with a namespace, separated from the key with a ':' character.
#  Values have a maximum length of 255 characters.
#  An application can have up to 10 entries per metadata field.
#  Entries written by applications are private and can only be read or modified by
#  the same
#  application.
#  For more information, see
#  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [square.rb::OrderLineItemModifier]
    def initialize(uid: OMIT, catalog_object_id: OMIT, catalog_version: OMIT, name: OMIT, quantity: OMIT, base_price_money: OMIT, total_price_money: OMIT, metadata: OMIT, additional_properties: nil)
      @uid = uid if uid != OMIT
      @catalog_object_id = catalog_object_id if catalog_object_id != OMIT
      @catalog_version = catalog_version if catalog_version != OMIT
      @name = name if name != OMIT
      @quantity = quantity if quantity != OMIT
      @base_price_money = base_price_money if base_price_money != OMIT
      @total_price_money = total_price_money if total_price_money != OMIT
      @metadata = metadata if metadata != OMIT
      @additional_properties = additional_properties
      @_field_set = { "uid": uid, "catalog_object_id": catalog_object_id, "catalog_version": catalog_version, "name": name, "quantity": quantity, "base_price_money": base_price_money, "total_price_money": total_price_money, "metadata": metadata }.reject do | _k, v |
  v == OMIT
end
    end
# Deserialize a JSON object to an instance of OrderLineItemModifier
    #
    # @param json_object [String] 
    # @return [square.rb::OrderLineItemModifier]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      uid = parsed_json["uid"]
      catalog_object_id = parsed_json["catalog_object_id"]
      catalog_version = parsed_json["catalog_version"]
      name = parsed_json["name"]
      quantity = parsed_json["quantity"]
      unless parsed_json["base_price_money"].nil?
        base_price_money = parsed_json["base_price_money"].to_json
        base_price_money = square.rb::Money.from_json(json_object: base_price_money)
      else
        base_price_money = nil
      end
      unless parsed_json["total_price_money"].nil?
        total_price_money = parsed_json["total_price_money"].to_json
        total_price_money = square.rb::Money.from_json(json_object: total_price_money)
      else
        total_price_money = nil
      end
      metadata = parsed_json["metadata"]
      new(
        uid: uid,
        catalog_object_id: catalog_object_id,
        catalog_version: catalog_version,
        name: name,
        quantity: quantity,
        base_price_money: base_price_money,
        total_price_money: total_price_money,
        metadata: metadata,
        additional_properties: struct
      )
    end
# Serialize an instance of OrderLineItemModifier to a JSON object
    #
    # @return [String]
    def to_json
      @_field_set&.to_json
    end
# Leveraged for Union-type generation, validate_raw attempts to parse the given
#  hash and check each fields type against the current object's property
#  definitions.
    #
    # @param obj [Object] 
    # @return [Void]
    def self.validate_raw(obj:)
      obj.uid&.is_a?(String) != false || raise("Passed value for field obj.uid is not the expected type, validation failed.")
      obj.catalog_object_id&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_id is not the expected type, validation failed.")
      obj.catalog_version&.is_a?(Long) != false || raise("Passed value for field obj.catalog_version is not the expected type, validation failed.")
      obj.name&.is_a?(String) != false || raise("Passed value for field obj.name is not the expected type, validation failed.")
      obj.quantity&.is_a?(String) != false || raise("Passed value for field obj.quantity is not the expected type, validation failed.")
      obj.base_price_money.nil? || square.rb::Money.validate_raw(obj: obj.base_price_money)
      obj.total_price_money.nil? || square.rb::Money.validate_raw(obj: obj.total_price_money)
      obj.metadata&.is_a?(Hash) != false || raise("Passed value for field obj.metadata is not the expected type, validation failed.")
    end
  end
end