# frozen_string_literal: true
require_relative "order_quantity_unit"
require_relative "order_line_item_item_type"
require_relative "order_line_item_modifier"
require_relative "order_line_item_applied_tax"
require_relative "order_line_item_applied_discount"
require_relative "order_line_item_applied_service_charge"
require_relative "money"
require_relative "order_line_item_pricing_blocklists"
require "ostruct"
require "json"

module square.rb
# Represents a line item in an order. Each line item describes a different
#  product to purchase, with its own quantity and price details.
  class OrderLineItem
  # @return [String] A unique ID that identifies the line item only within this order.
    attr_reader :uid
  # @return [String] The name of the line item.
    attr_reader :name
  # @return [String] The count, or measurement, of a line item being purchased:
#  If `quantity` is a whole number, and `quantity_unit` is not specified, then
#  `quantity` denotes an item count.  For example: `3` apples.
#  If `quantity` is a whole or decimal number, and `quantity_unit` is also
#  specified, then `quantity` denotes a measurement.  For example: `2.25` pounds of
#  broccoli.
#  For more information, see [Specify item quantity and measurement
#  p.com/docs/orders-api/create-orders#specify-item-quantity-and-measurement-unit).
#  Line items with a quantity of `0` are automatically removed
#  when paying for or otherwise completing the order.
    attr_reader :quantity
  # @return [square.rb::OrderQuantityUnit] The measurement unit and decimal precision that this line item's quantity is
#  measured in.
    attr_reader :quantity_unit
  # @return [String] An optional note associated with the line item.
    attr_reader :note
  # @return [String] The [CatalogItemVariation](entity:CatalogItemVariation) ID applied to this line
#  item.
    attr_reader :catalog_object_id
  # @return [Long] The version of the catalog object that this line item references.
    attr_reader :catalog_version
  # @return [String] The name of the variation applied to this line item.
    attr_reader :variation_name
  # @return [square.rb::OrderLineItemItemType] The type of line item: an itemized sale, a non-itemized sale (custom amount), or
#  the
#  activation or reloading of a gift card.
#  See [OrderLineItemItemType](#type-orderlineitemitemtype) for possible values
    attr_reader :item_type
  # @return [Hash{String => String}] Application-defined data attached to this line item. Metadata fields are
#  intended
#  to store descriptive references or associations with an entity in another system
#  or store brief
#  information about the object. Square does not process this field; it only stores
#  and returns it
#  in relevant API calls. Do not use metadata to store any sensitive information
#  (such as personally
#  identifiable information or card details).
#  Keys written by applications must be 60 characters or less and must be in the
#  character set
#  `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These
#  keys are prefixed
#  with a namespace, separated from the key with a ':' character.
#  Values have a maximum length of 255 characters.
#  An application can have up to 10 entries per metadata field.
#  Entries written by applications are private and can only be read or modified by
#  the same
#  application.
#  For more information, see
#  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    attr_reader :metadata
  # @return [Array<square.rb::OrderLineItemModifier>] The [CatalogModifier](entity:CatalogModifier)s applied to this line item.
    attr_reader :modifiers
  # @return [Array<square.rb::OrderLineItemAppliedTax>] The list of references to taxes applied to this line item. Each
#  `OrderLineItemAppliedTax` has a `tax_uid` that references the `uid` of a
#  top-level `OrderLineItemTax` applied to the line item. On reads, the
#  amount applied is populated.
#  An `OrderLineItemAppliedTax` is automatically created on every line
#  item for all `ORDER` scoped taxes added to the order. `OrderLineItemAppliedTax`
#  records for `LINE_ITEM` scoped taxes must be added in requests for the tax
#  to apply to any line items.
#  To change the amount of a tax, modify the referenced top-level tax.
    attr_reader :applied_taxes
  # @return [Array<square.rb::OrderLineItemAppliedDiscount>] The list of references to discounts applied to this line item. Each
#  `OrderLineItemAppliedDiscount` has a `discount_uid` that references the `uid` of
#  a top-level
#  `OrderLineItemDiscounts` applied to the line item. On reads, the amount
#  applied is populated.
#  An `OrderLineItemAppliedDiscount` is automatically created on every line item
#  for all
#  `ORDER` scoped discounts that are added to the order.
#  `OrderLineItemAppliedDiscount` records
#  for `LINE_ITEM` scoped discounts must be added in requests for the discount to
#  apply to any
#  line items.
#  To change the amount of a discount, modify the referenced top-level discount.
    attr_reader :applied_discounts
  # @return [Array<square.rb::OrderLineItemAppliedServiceCharge>] The list of references to service charges applied to this line item. Each
#  `OrderLineItemAppliedServiceCharge` has a `service_charge_id` that references
#  the `uid` of a
#  top-level `OrderServiceCharge` applied to the line item. On reads, the amount
#  applied is
#  populated.
#  To change the amount of a service charge, modify the referenced top-level
#  service charge.
    attr_reader :applied_service_charges
  # @return [square.rb::Money] The base price for a single unit of the line item.
    attr_reader :base_price_money
  # @return [square.rb::Money] The total price of all item variations sold in this line item.
#  The price is calculated as `base_price_money` multiplied by `quantity`.
#  It does not include modifiers.
    attr_reader :variation_total_price_money
  # @return [square.rb::Money] The amount of money made in gross sales for this line item.
#  The amount is calculated as the sum of the variation's total price and each
#  modifier's total price.
#  For inclusive tax items in the US, Canada, and Japan, tax is deducted from
#  `gross_sales_money`. For Europe and
#  Australia, inclusive tax remains as part of the gross sale calculation.
    attr_reader :gross_sales_money
  # @return [square.rb::Money] The total amount of tax money to collect for the line item.
    attr_reader :total_tax_money
  # @return [square.rb::Money] The total amount of discount money to collect for the line item.
    attr_reader :total_discount_money
  # @return [square.rb::Money] The total amount of money to collect for this line item.
    attr_reader :total_money
  # @return [square.rb::OrderLineItemPricingBlocklists] Describes pricing adjustments that are blocked from automatic
#  application to a line item. For more information, see
#  [Apply Taxes and
#  unts](https://developer.squareup.com/docs/orders-api/apply-taxes-and-discounts).
    attr_reader :pricing_blocklists
  # @return [square.rb::Money] The total amount of apportioned service charge money to collect for the line
#  item.
    attr_reader :total_service_charge_money
  # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
  # @return [Object] 
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param uid [String] A unique ID that identifies the line item only within this order.
    # @param name [String] The name of the line item.
    # @param quantity [String] The count, or measurement, of a line item being purchased:
#  If `quantity` is a whole number, and `quantity_unit` is not specified, then
#  `quantity` denotes an item count.  For example: `3` apples.
#  If `quantity` is a whole or decimal number, and `quantity_unit` is also
#  specified, then `quantity` denotes a measurement.  For example: `2.25` pounds of
#  broccoli.
#  For more information, see [Specify item quantity and measurement
#  p.com/docs/orders-api/create-orders#specify-item-quantity-and-measurement-unit).
#  Line items with a quantity of `0` are automatically removed
#  when paying for or otherwise completing the order.
    # @param quantity_unit [square.rb::OrderQuantityUnit] The measurement unit and decimal precision that this line item's quantity is
#  measured in.
    # @param note [String] An optional note associated with the line item.
    # @param catalog_object_id [String] The [CatalogItemVariation](entity:CatalogItemVariation) ID applied to this line
#  item.
    # @param catalog_version [Long] The version of the catalog object that this line item references.
    # @param variation_name [String] The name of the variation applied to this line item.
    # @param item_type [square.rb::OrderLineItemItemType] The type of line item: an itemized sale, a non-itemized sale (custom amount), or
#  the
#  activation or reloading of a gift card.
#  See [OrderLineItemItemType](#type-orderlineitemitemtype) for possible values
    # @param metadata [Hash{String => String}] Application-defined data attached to this line item. Metadata fields are
#  intended
#  to store descriptive references or associations with an entity in another system
#  or store brief
#  information about the object. Square does not process this field; it only stores
#  and returns it
#  in relevant API calls. Do not use metadata to store any sensitive information
#  (such as personally
#  identifiable information or card details).
#  Keys written by applications must be 60 characters or less and must be in the
#  character set
#  `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These
#  keys are prefixed
#  with a namespace, separated from the key with a ':' character.
#  Values have a maximum length of 255 characters.
#  An application can have up to 10 entries per metadata field.
#  Entries written by applications are private and can only be read or modified by
#  the same
#  application.
#  For more information, see
#  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    # @param modifiers [Array<square.rb::OrderLineItemModifier>] The [CatalogModifier](entity:CatalogModifier)s applied to this line item.
    # @param applied_taxes [Array<square.rb::OrderLineItemAppliedTax>] The list of references to taxes applied to this line item. Each
#  `OrderLineItemAppliedTax` has a `tax_uid` that references the `uid` of a
#  top-level `OrderLineItemTax` applied to the line item. On reads, the
#  amount applied is populated.
#  An `OrderLineItemAppliedTax` is automatically created on every line
#  item for all `ORDER` scoped taxes added to the order. `OrderLineItemAppliedTax`
#  records for `LINE_ITEM` scoped taxes must be added in requests for the tax
#  to apply to any line items.
#  To change the amount of a tax, modify the referenced top-level tax.
    # @param applied_discounts [Array<square.rb::OrderLineItemAppliedDiscount>] The list of references to discounts applied to this line item. Each
#  `OrderLineItemAppliedDiscount` has a `discount_uid` that references the `uid` of
#  a top-level
#  `OrderLineItemDiscounts` applied to the line item. On reads, the amount
#  applied is populated.
#  An `OrderLineItemAppliedDiscount` is automatically created on every line item
#  for all
#  `ORDER` scoped discounts that are added to the order.
#  `OrderLineItemAppliedDiscount` records
#  for `LINE_ITEM` scoped discounts must be added in requests for the discount to
#  apply to any
#  line items.
#  To change the amount of a discount, modify the referenced top-level discount.
    # @param applied_service_charges [Array<square.rb::OrderLineItemAppliedServiceCharge>] The list of references to service charges applied to this line item. Each
#  `OrderLineItemAppliedServiceCharge` has a `service_charge_id` that references
#  the `uid` of a
#  top-level `OrderServiceCharge` applied to the line item. On reads, the amount
#  applied is
#  populated.
#  To change the amount of a service charge, modify the referenced top-level
#  service charge.
    # @param base_price_money [square.rb::Money] The base price for a single unit of the line item.
    # @param variation_total_price_money [square.rb::Money] The total price of all item variations sold in this line item.
#  The price is calculated as `base_price_money` multiplied by `quantity`.
#  It does not include modifiers.
    # @param gross_sales_money [square.rb::Money] The amount of money made in gross sales for this line item.
#  The amount is calculated as the sum of the variation's total price and each
#  modifier's total price.
#  For inclusive tax items in the US, Canada, and Japan, tax is deducted from
#  `gross_sales_money`. For Europe and
#  Australia, inclusive tax remains as part of the gross sale calculation.
    # @param total_tax_money [square.rb::Money] The total amount of tax money to collect for the line item.
    # @param total_discount_money [square.rb::Money] The total amount of discount money to collect for the line item.
    # @param total_money [square.rb::Money] The total amount of money to collect for this line item.
    # @param pricing_blocklists [square.rb::OrderLineItemPricingBlocklists] Describes pricing adjustments that are blocked from automatic
#  application to a line item. For more information, see
#  [Apply Taxes and
#  unts](https://developer.squareup.com/docs/orders-api/apply-taxes-and-discounts).
    # @param total_service_charge_money [square.rb::Money] The total amount of apportioned service charge money to collect for the line
#  item.
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [square.rb::OrderLineItem]
    def initialize(uid: OMIT, name: OMIT, quantity:, quantity_unit: OMIT, note: OMIT, catalog_object_id: OMIT, catalog_version: OMIT, variation_name: OMIT, item_type: OMIT, metadata: OMIT, modifiers: OMIT, applied_taxes: OMIT, applied_discounts: OMIT, applied_service_charges: OMIT, base_price_money: OMIT, variation_total_price_money: OMIT, gross_sales_money: OMIT, total_tax_money: OMIT, total_discount_money: OMIT, total_money: OMIT, pricing_blocklists: OMIT, total_service_charge_money: OMIT, additional_properties: nil)
      @uid = uid if uid != OMIT
      @name = name if name != OMIT
      @quantity = quantity
      @quantity_unit = quantity_unit if quantity_unit != OMIT
      @note = note if note != OMIT
      @catalog_object_id = catalog_object_id if catalog_object_id != OMIT
      @catalog_version = catalog_version if catalog_version != OMIT
      @variation_name = variation_name if variation_name != OMIT
      @item_type = item_type if item_type != OMIT
      @metadata = metadata if metadata != OMIT
      @modifiers = modifiers if modifiers != OMIT
      @applied_taxes = applied_taxes if applied_taxes != OMIT
      @applied_discounts = applied_discounts if applied_discounts != OMIT
      @applied_service_charges = applied_service_charges if applied_service_charges != OMIT
      @base_price_money = base_price_money if base_price_money != OMIT
      @variation_total_price_money = variation_total_price_money if variation_total_price_money != OMIT
      @gross_sales_money = gross_sales_money if gross_sales_money != OMIT
      @total_tax_money = total_tax_money if total_tax_money != OMIT
      @total_discount_money = total_discount_money if total_discount_money != OMIT
      @total_money = total_money if total_money != OMIT
      @pricing_blocklists = pricing_blocklists if pricing_blocklists != OMIT
      @total_service_charge_money = total_service_charge_money if total_service_charge_money != OMIT
      @additional_properties = additional_properties
      @_field_set = { "uid": uid, "name": name, "quantity": quantity, "quantity_unit": quantity_unit, "note": note, "catalog_object_id": catalog_object_id, "catalog_version": catalog_version, "variation_name": variation_name, "item_type": item_type, "metadata": metadata, "modifiers": modifiers, "applied_taxes": applied_taxes, "applied_discounts": applied_discounts, "applied_service_charges": applied_service_charges, "base_price_money": base_price_money, "variation_total_price_money": variation_total_price_money, "gross_sales_money": gross_sales_money, "total_tax_money": total_tax_money, "total_discount_money": total_discount_money, "total_money": total_money, "pricing_blocklists": pricing_blocklists, "total_service_charge_money": total_service_charge_money }.reject do | _k, v |
  v == OMIT
end
    end
# Deserialize a JSON object to an instance of OrderLineItem
    #
    # @param json_object [String] 
    # @return [square.rb::OrderLineItem]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      uid = parsed_json["uid"]
      name = parsed_json["name"]
      quantity = parsed_json["quantity"]
      unless parsed_json["quantity_unit"].nil?
        quantity_unit = parsed_json["quantity_unit"].to_json
        quantity_unit = square.rb::OrderQuantityUnit.from_json(json_object: quantity_unit)
      else
        quantity_unit = nil
      end
      note = parsed_json["note"]
      catalog_object_id = parsed_json["catalog_object_id"]
      catalog_version = parsed_json["catalog_version"]
      variation_name = parsed_json["variation_name"]
      item_type = parsed_json["item_type"]
      metadata = parsed_json["metadata"]
      modifiers = parsed_json["modifiers"]&.map do | item |
  item = item.to_json
  square.rb::OrderLineItemModifier.from_json(json_object: item)
end
      applied_taxes = parsed_json["applied_taxes"]&.map do | item |
  item = item.to_json
  square.rb::OrderLineItemAppliedTax.from_json(json_object: item)
end
      applied_discounts = parsed_json["applied_discounts"]&.map do | item |
  item = item.to_json
  square.rb::OrderLineItemAppliedDiscount.from_json(json_object: item)
end
      applied_service_charges = parsed_json["applied_service_charges"]&.map do | item |
  item = item.to_json
  square.rb::OrderLineItemAppliedServiceCharge.from_json(json_object: item)
end
      unless parsed_json["base_price_money"].nil?
        base_price_money = parsed_json["base_price_money"].to_json
        base_price_money = square.rb::Money.from_json(json_object: base_price_money)
      else
        base_price_money = nil
      end
      unless parsed_json["variation_total_price_money"].nil?
        variation_total_price_money = parsed_json["variation_total_price_money"].to_json
        variation_total_price_money = square.rb::Money.from_json(json_object: variation_total_price_money)
      else
        variation_total_price_money = nil
      end
      unless parsed_json["gross_sales_money"].nil?
        gross_sales_money = parsed_json["gross_sales_money"].to_json
        gross_sales_money = square.rb::Money.from_json(json_object: gross_sales_money)
      else
        gross_sales_money = nil
      end
      unless parsed_json["total_tax_money"].nil?
        total_tax_money = parsed_json["total_tax_money"].to_json
        total_tax_money = square.rb::Money.from_json(json_object: total_tax_money)
      else
        total_tax_money = nil
      end
      unless parsed_json["total_discount_money"].nil?
        total_discount_money = parsed_json["total_discount_money"].to_json
        total_discount_money = square.rb::Money.from_json(json_object: total_discount_money)
      else
        total_discount_money = nil
      end
      unless parsed_json["total_money"].nil?
        total_money = parsed_json["total_money"].to_json
        total_money = square.rb::Money.from_json(json_object: total_money)
      else
        total_money = nil
      end
      unless parsed_json["pricing_blocklists"].nil?
        pricing_blocklists = parsed_json["pricing_blocklists"].to_json
        pricing_blocklists = square.rb::OrderLineItemPricingBlocklists.from_json(json_object: pricing_blocklists)
      else
        pricing_blocklists = nil
      end
      unless parsed_json["total_service_charge_money"].nil?
        total_service_charge_money = parsed_json["total_service_charge_money"].to_json
        total_service_charge_money = square.rb::Money.from_json(json_object: total_service_charge_money)
      else
        total_service_charge_money = nil
      end
      new(
        uid: uid,
        name: name,
        quantity: quantity,
        quantity_unit: quantity_unit,
        note: note,
        catalog_object_id: catalog_object_id,
        catalog_version: catalog_version,
        variation_name: variation_name,
        item_type: item_type,
        metadata: metadata,
        modifiers: modifiers,
        applied_taxes: applied_taxes,
        applied_discounts: applied_discounts,
        applied_service_charges: applied_service_charges,
        base_price_money: base_price_money,
        variation_total_price_money: variation_total_price_money,
        gross_sales_money: gross_sales_money,
        total_tax_money: total_tax_money,
        total_discount_money: total_discount_money,
        total_money: total_money,
        pricing_blocklists: pricing_blocklists,
        total_service_charge_money: total_service_charge_money,
        additional_properties: struct
      )
    end
# Serialize an instance of OrderLineItem to a JSON object
    #
    # @return [String]
    def to_json
      @_field_set&.to_json
    end
# Leveraged for Union-type generation, validate_raw attempts to parse the given
#  hash and check each fields type against the current object's property
#  definitions.
    #
    # @param obj [Object] 
    # @return [Void]
    def self.validate_raw(obj:)
      obj.uid&.is_a?(String) != false || raise("Passed value for field obj.uid is not the expected type, validation failed.")
      obj.name&.is_a?(String) != false || raise("Passed value for field obj.name is not the expected type, validation failed.")
      obj.quantity.is_a?(String) != false || raise("Passed value for field obj.quantity is not the expected type, validation failed.")
      obj.quantity_unit.nil? || square.rb::OrderQuantityUnit.validate_raw(obj: obj.quantity_unit)
      obj.note&.is_a?(String) != false || raise("Passed value for field obj.note is not the expected type, validation failed.")
      obj.catalog_object_id&.is_a?(String) != false || raise("Passed value for field obj.catalog_object_id is not the expected type, validation failed.")
      obj.catalog_version&.is_a?(Long) != false || raise("Passed value for field obj.catalog_version is not the expected type, validation failed.")
      obj.variation_name&.is_a?(String) != false || raise("Passed value for field obj.variation_name is not the expected type, validation failed.")
      obj.item_type&.is_a?(square.rb::OrderLineItemItemType) != false || raise("Passed value for field obj.item_type is not the expected type, validation failed.")
      obj.metadata&.is_a?(Hash) != false || raise("Passed value for field obj.metadata is not the expected type, validation failed.")
      obj.modifiers&.is_a?(Array) != false || raise("Passed value for field obj.modifiers is not the expected type, validation failed.")
      obj.applied_taxes&.is_a?(Array) != false || raise("Passed value for field obj.applied_taxes is not the expected type, validation failed.")
      obj.applied_discounts&.is_a?(Array) != false || raise("Passed value for field obj.applied_discounts is not the expected type, validation failed.")
      obj.applied_service_charges&.is_a?(Array) != false || raise("Passed value for field obj.applied_service_charges is not the expected type, validation failed.")
      obj.base_price_money.nil? || square.rb::Money.validate_raw(obj: obj.base_price_money)
      obj.variation_total_price_money.nil? || square.rb::Money.validate_raw(obj: obj.variation_total_price_money)
      obj.gross_sales_money.nil? || square.rb::Money.validate_raw(obj: obj.gross_sales_money)
      obj.total_tax_money.nil? || square.rb::Money.validate_raw(obj: obj.total_tax_money)
      obj.total_discount_money.nil? || square.rb::Money.validate_raw(obj: obj.total_discount_money)
      obj.total_money.nil? || square.rb::Money.validate_raw(obj: obj.total_money)
      obj.pricing_blocklists.nil? || square.rb::OrderLineItemPricingBlocklists.validate_raw(obj: obj.pricing_blocklists)
      obj.total_service_charge_money.nil? || square.rb::Money.validate_raw(obj: obj.total_service_charge_money)
    end
  end
end