
module Square
  class Product
    include Square::Internal::Types::Enum
    SQUARE_POS = "SQUARE_POS"
    EXTERNAL_API = "EXTERNAL_API"
    BILLING = "BILLING"
    APPOINTMENTS = "APPOINTMENTS"
    INVOICES = "INVOICES"
    ONLINE_STORE = "ONLINE_STORE"
    PAYROLL = "PAYROLL"
    DASHBOARD = "DASHBOARD"
    ITEM_LIBRARY_IMPORT = "ITEM_LIBRARY_IMPORT"
    OTHER = "OTHER"
  end
end
