# frozen_string_literal: true

module Square
  module Types
    module ReferenceType
      extend Square::Internal::Types::Enum

      UNKNOWN_TYPE = "UNKNOWN_TYPE"
      LOCATION = "LOCATION"
      FIRST_PARTY_INTEGRATION = "FIRST_PARTY_INTEGRATION"
      OAUTH_APPLICATION = "OAUTH_APPLICATION"
      ONLINE_SITE = "ONLINE_SITE"
      ONLINE_CHECKOUT = "ONLINE_CHECKOUT"
      INVOICE = "INVOICE"
      GIFT_CARD = "GIFT_CARD"
      GIFT_CARD_MARKETPLACE = "GIFT_CARD_MARKETPLACE"
      RECURRING_SUBSCRIPTION = "RECURRING_SUBSCRIPTION"
      ONLINE_BOOKING_FLOW = "ONLINE_BOOKING_FLOW"
      SQUARE_ASSISTANT = "SQUARE_ASSISTANT"
      CASH_LOCAL = "CASH_LOCAL"
      POINT_OF_SALE = "POINT_OF_SALE"
      KIOSK = "KIOSK"
    end
  end
end
