# square
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'api_test_base'

class LocationsApiTests < ApiTestBase
  # Called only once for the class before any test has executed
  def setup
    @response_catcher = HttpResponseCatcher.new
    @controller = LocationsApi.new CONFIG, http_call_back: @response_catcher
  end

  # Provides the details for all of a business's locations.
  #
  #Most other Connect API endpoints have a required `location_id` path parameter.
  #The `id` field of the [`Location`](#type-location) objects returned by this
  #endpoint correspond to that `location_id` parameter.
  def test_test_list_locations()

    # Perform the API call through the SDK function
    result = @controller.list_locations()

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(TestHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end
