name: Setup Ruby Environment

on:
  workflow_call:
    inputs:
      ruby-version:
        description: 'Ruby version to use'
        required: false
        default: '3.3'
        type: string
      bundler-version:
        description: 'Bundler version to use'
        required: false
        default: '2.4'
        type: string
    outputs:
      ruby-version:
        description: 'The Ruby version that was set up'
        value: ${{ steps.setup-ruby.outputs.ruby-version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        id: setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-version: ${{ inputs.bundler-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install
